spring:
    datasource:
        #driverClassName: org.h2.Driver
        driverClassName: com.mysql.cj.jdbc.Driver
        password: root
        url: jdbc:mysql://localhost:3306/dlsdb?serverTimezone=UTC
        #url: jdbc:h2:mem:dlsdb
        username: root
    jpa:
        #database-platform: org.hibernate.dialect.H2Dialect
        database-platform: org.hibernate.dialect.MySQL5Dialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                generate_statistics: false
        show-sql: true
    h2:
        console:
            enabled: true
    thymeleaf:
        cache: false
