spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: dlsinventory
        url: jdbc:mysql://db4free.net/dlsinventory?serverTimezone=UTC
        username: dlsinventory
    jpa:
        #database-platform: org.hibernate.dialect.H2Dialect
        database-platform: org.hibernate.dialect.MySQL5Dialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                generate_statistics: false
        show-sql: true
    h2:
        console:
            enabled: true
    thymeleaf:
        cache: false
