spring:
    datasource:
        #driverClassName: org.h2.Driver
        driverClassName: com.mysql.cj.jdbc.Driver
        password: f18b45e9
        url: jdbc:mysql://us-cdbr-east-05.cleardb.net:3306/heroku_c754a503c6f585e?serverTimezone=UTC
        #url: jdbc:h2:mem:dlsdb
        username: b10cf634f64730
    jpa:
        #database-platform: org.hibernate.dialect.H2Dialect
        database-platform: org.hibernate.dialect.MySQL5Dialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                generate_statistics: false
        show-sql: true
    h2:
        console:
            enabled: true
    thymeleaf:
        cache: false
